services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret_key
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=admin
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules 